#!/usr/bin/env sh

consul-template -once -template "/root/rsyncd_password_file.template:/etc/rsyncd_password_file"
chmod 0600 /etc/rsyncd_password_file

duplicity --no-encryption --full-if-older-than="1M" --rsync-options="--password-file=/etc/rsyncd_password_file" $BACKUP_SOURCE rsync://${BACKUP_TARGET_USER}@${BACKUP_TARGET_HOST}::/${BACKUP_TARGET_MODULE}${BACKUP_TARGET_PATH}/
